export enum ASSETS {
  FETCH = "FETCH_ASSETS",
  FETCH_BY_SYMBOL = "FETCH_ASSETS_BY_SYMBOL",
}

export enum TRANSACTIONS {
  FETCH = "FETCH_TRANSACTIONS",
}

export enum POSITIONS {
  FETCH = "FETCH_POSITIONS",
}
